### ISSUE TITLE
collectd-write_http package doesn't always exist for RedHat derivatives

### ISSUE THREAD

**Issue by simonpasquier** [pdxcat/puppet-module-collectd#251]
A few months ago, there's been a change (https://github.com/pdxcat/puppet-module-collectd/commit/a334b6e989acb988b2783d90e91c99ab7cff8e88) that installed the collectd-write_http package for RedHat platforms. Unfortunately this package doesn't always exist depending on the repository. For instance, Fedora and EPEL repos have no such package [1] since the write_http plugin is included in the core collectd package.

I suggest to revert the commit (https://github.com/pdxcat/puppet-module-collectd/commit/a334b6e989acb988b2783d90e91c99ab7cff8e88) since it is always possible to install the package outside of the collectd manifest.

[1] https://apps.fedoraproject.org/packages/collectd/overview/

**Comment by sijis** [comment]
I submitted the PR in question here. Sorry for the adverse effect here.

In situations where there's a conflict, I could update those changes to include a param to the class named 'manage_package' and set it to true, as default. This would allow the module to load it but also allow for other modules to control the package installation as desired.

**Comment by simonpasquier** [comment]
@sijis no problem. Indeed adding a class param would be neat to support both cases.
