### ISSUE TITLE
write-graphite module: Invalid configuration option: LogSendErrors

### ISSUE THREAD

**Issue by daks** [pdxcat/puppet-module-collectd#253]
Hello,

I just upgraded this module from 2.1.0 to 3.2.0 and running it on Debian Wheezy. I use the graphite module with a configuration like

    class { 'collectd::plugin::write_graphite':
        graphitehost    => 'xxx.xxx.xxx.xxx',
        graphiteport    => '2003',
        graphiteprefix  => 'servers.',
    }

This configuration worked before and seems to still work but it raises an error when running collectd:

    collectd[3910]: write_graphite plugin: Invalid configuration option: LogSendErrors.

I tried to set this option to true or false and I got the same error, only removing this option resolves it. Collectd version on Debian 7 is 5.1.0

**Comment by txaj** [comment]
please give us the output of : 
{code}
# collectd -h
{code}

as well as the complete block generated with the LogSendErrors option

**Comment by daks** [comment]
# collectd -h
Usage: collectd [OPTIONS]

Available options:
  General:
    -C <file>       Configuration file.
                    Default: /etc/collectd/collectd.conf
    -t              Test config and exit.
    -T              Test plugin read and exit.
    -P <file>       PID-file.
                    Default: /var/run/collectd.pid
    -f              Don't fork to the background.
    -h              Display help (this message)

Builtin defaults:
  Config file       /etc/collectd/collectd.conf
  PID file          /var/run/collectd.pid
  Plugin directory  /usr/lib/collectd
  Data directory    /var/lib/collectd

collectd 5.1.0, http://collectd.org/
by Florian octo Forster <octo@verplant.org>
for contributions see `AUTHORS'

**Comment by daks** [comment]
# more 10-write_graphite.conf 
# Generated by Puppet
LoadPlugin write_graphite

<Plugin write_graphite>
  <Carbon>
    Host "xxx"
    Port "2003"
    Prefix "serveurs."
    EscapeCharacter "_"
    StoreRates true
    AlwaysAppendDS false
    SeparateInstances false
    LogSendErrors true
  </Carbon>
</Plugin>

**Comment by txaj** [comment]
That was fixed by 3f60606f8053f01f607f56905aff7ea45e5fa0a5

This fix is not yet in a release but you can checkout master up to this commit if you wish, or cherry-pick it

**Comment by daks** [comment]
thanks for your quick answer. is next release due soon? i would prefer only use tagged release not master.

**Comment by txaj** [comment]
@blkperl ?

**Comment by aamerik** [comment]
Please publish this fix to puppet forge :) thank you :+1:

**Comment by blkperl** [comment]
Ok, working on it

**Comment by daks** [comment]
thank you for you reactivity :)

**Comment by blkperl** [comment]
New release is out
