### ISSUE TITLE
Support puppet 4

### ISSUE THREAD

**Issue by txaj** [pdxcat/puppet-module-collectd#257]
I started testing against puppet 4

As of today stdlib does not support puppet4. It will be supported with the release of stdlib 5.0. current master branch of stdlib does not even tests on travis against puppet 4, and I got a bunch of errors that seems to come from stdlib

**Comment by blkperl** [comment]
Ok we will support Puppet 4, when stdlib is ready

**Comment by blkperl** [comment]
@txaj any updates?

**Comment by txaj** [comment]
https://github.com/pdxcat/puppet-module-collectd/commit/63bf721c499ee27b219659218c110b3f0049bbc1

you added travis testing with v4 and it works, so I guess this can be closed ? I only see two depreciation warning ( https://travis-ci.org/pdxcat/puppet-module-collectd/jobs/73962930 ), you can leave this bug open to think of taking care of those

**Comment by blkperl** [comment]
The deprecation warnings are for rspec not Puppet
