### ISSUE TITLE
custom plugin install?

### ISSUE THREAD

**Issue by aamerik** [pdxcat/puppet-module-collectd#268]
Hello. Im looking to use https://collectd.org/wiki/index.php/Plugin:Aggregation/Config using your module can you tell me if this is possible?  I dont see a way to add custom plugin defs. Thank you

**Comment by txaj** [comment]
This is a standard plugin (https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_aggregation) that could be supported by this module -- but is currently not. 

You need to implement the plugin in this module. Feel free to PR. Read the bottom of the README for some basic guidance. Feel free to ask for pointers if needed

**Comment by aamerik** [comment]
Txaj,

Thank you for your response, I'm trying to implement this but I'm running into a design issue.
Technically this plugin can be used to aggregate the values of many other plugins, so its possible that more than one instance of the class will be applied to the host.  I'm having issues understanding how to best support that usecase. This is what I have so far:

```
# https://collectd.org/wiki/index.php/Plugin:Aggregation
class collectd::plugin::aggregation (
  $ensure   = present,
  $interval = undef,
  $plugin   = undef,
  $type     = undef,
  $groupby  = undef,
  $calcsum  = undef,
  $calcavg  = undef,
) {
  collectd::plugin { "aggregation":
    ensure   => $ensure,
    content  => template('collectd/plugin/aggregation.conf.erb'),
    interval => $interval,
  }
}
```

**Comment by txaj** [comment]
look at the collectd::plugin defined type ; there is several arguments you can pass (especially the priority one) that you could make use of 

If I understand well you can have 0..n <Aggregation> blocks ? If yes you can look for example in plugins like curl, postgresql or python on how we solved that. This is an advanced pattern indeed :-)

**Comment by kurpipio** [comment]
I created pull request for that https://github.com/pdxcat/puppet-module-collectd/pull/289
