### ISSUE TITLE
Allow ensure => absent

### ISSUE THREAD

**Issue by moutons** [pdxcat/puppet-module-collectd#271]
Sometimes I'd like to remove collectd but leave the rest of the node as it is. It'd be nice to be able to purge it using the module.

**Comment by txaj** [comment]
Unless proven otherwise I'm against supporting a full removal. This is the approach Puppetlabs is following on the pgsql module, you can refer to their arguments https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/CHANGELOG.md#uninstallation-removal

**Comment by blkperl** [comment]
Sorry, not going to support these feature.
