### ISSUE TITLE
Support multiple exec statements

### ISSUE THREAD

**Issue by deric** [pdxcat/puppet-module-collectd#286]
Current implementation does not support complete definition of `exec` plugin (from wiki):
```
<Plugin exec>
  Exec "myuser:mygroup" "myprog"
  Exec "otheruser" "/path/to/another/binary" "arg0" "arg1"
  NotificationExec "user" "/usr/lib/collectd/exec/handle_notification"
</Plugin>
```
Only one `Exec` statement could be defined.

Moreover there's a missing space between arguments ([see line 6](https://github.com/pdxcat/puppet-module-collectd/blob/master/templates/exec.conf.erb#L6))
```ruby
<% @exec.each do |exec| -%>"<%= exec %>"<% end -%>
```

**Comment by blkperl** [comment]
This was merged in.
