### ISSUE TITLE
Using collectd::plugin::curl_json in a define results in Puppet duplicate declaration errors

### ISSUE THREAD

**Issue by aamerik** [pdxcat/puppet-module-collectd#290]
Hello, I'm trying to use the curl_json module inside a define, passing it an array to iterate over, however it faisl with dup declaration on the Package resource.  Can the package resource be moved elsewhere to avoid this?

Thank you

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Package[collectd-curl_json] is already declared in file /etc/puppet/environments/lab1/modules/collectd/manifests/plugin/curl_json.pp:18; cannot redeclare at /etc/puppet/environments/lab1/modules/collectd/manifests/plugin/curl_json.pp:18 on node rmq001.lab1.ca1.sfmc.co
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by txaj** [comment]
This was introduced by #223

indeed that sucks to declare package{} inside defines ...... that should have not been done

**Comment by txaj** [comment]
PR welcome to rewrite curl_json the same way curl got rewritten - it'd solve this for this plugin

**Comment by blkperl** [comment]
Fixed in v4.0.0
